[theme]
primaryColor = "#0EA5E9"
backgroundColor = "#0A1929"
secondaryBackgroundColor = "#0C2D48"
textColor = "#E0F2FE"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
